version: "3.5"




services:

  verification-bot-api:
    depends_on:
      - verification-bot-redis
      - verification-bot-mongo
    image: verification-bot-api
    container_name: verification-bot-api
    restart: unless-stopped
    ports:
      - 127.0.0.212:8080:3000
      - 127.0.0.212:8081:4000
    volumes:
      - /data/static/verification-bot-api:/www/verification-bot-api/static
      - /data/logs/verification-bot-api:/www/verification-bot-api/logs
    networks:
      - verification-bot-api
      - verification-bot-api-proxy


  verification-bot-redis:
    image: redis
    container_name: verification-bot-redis
    restart: unless-stopped
    ports:
      - 127.0.0.212:6379:6379
    volumes:
      - /databases/redis/verification-bot:/data
    networks:
      - verification-bot-api-proxy
      - verification-bot-api


  verification-bot-mongo:
    image: mongo
    container_name: verification-bot-mongo
    restart: unless-stopped
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=****
#      - MONGO_INITDB_ROOT_PASSWORD=****
    ports:
      - 127.0.0.212:27017:27017
    volumes:
      - /databases/mongo/verification-bot:/data/db
    networks:
      - verification-bot-api-proxy
      - verification-bot-api


networks:
  verification-bot-api:
    driver: bridge
  verification-bot-api-proxy:
    external:
      name: verification-bot-api-proxy