version: "3.5"




services:

  parkinson-bot-redis:
    image: redis
    container_name: parkinson-bot-redis
    restart: unless-stopped
    ports:
      - 127.0.0.212:6379:6379
    volumes:
      - /databases/redis/parkinson-bot:/data
    networks:
      - parkinson


  parkinson-bot-mongo:
    image: mongo
    container_name: parkinson-bot-mongo
    restart: unless-stopped
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=****
#      - MONGO_INITDB_ROOT_PASSWORD=****
    ports:
      - 127.0.0.212:27017:27017
    volumes:
      - /databases/mongo/parkinson-bot:/data/db
    networks:
      - parkinson


networks:
  parkinson:
    driver: bridge
